const express=require('express');
const db=require('../config/db');
const {auth}=require('../middleware/auth');
const audit=require('../utils/audit');
const router=express.Router(); router.use(auth);
router.get('/',async(req,res)=>{try{let sql=`SELECT v.*, p.nome paciente_nome, u.nome usuario_nome, u.email usuario_email FROM vinculos_cuidado v JOIN usuarios p ON p.id=v.paciente_id JOIN usuarios u ON u.id=v.usuario_id WHERE (v.paciente_id=? OR v.usuario_id=?) ORDER BY v.id DESC`;const [rows]=await db.execute(sql,[req.user.id,req.user.id]);res.json(rows);}catch(e){res.status(500).json({error:'Erro ao consultar vínculos.'});}});
router.post('/request',async(req,res)=>{try{const email=String(req.body?.email||'').trim().toLowerCase();if(!email)return res.status(400).json({error:'Informe o e-mail.'});if(!['cuidador','responsavel','profissional'].includes(req.user.tipo))return res.status(403).json({error:'Este perfil não solicita vínculos.'});const [p]=await db.execute('SELECT id FROM usuarios WHERE email=? AND tipo=\'paciente\' LIMIT 1',[email]);if(!p.length)return res.status(404).json({error:'Paciente não encontrado.'});const pid=p[0].id;await db.execute(`INSERT INTO vinculos_cuidado (paciente_id,usuario_id,papel,permissoes,status) VALUES (?,?,?,?, 'pendente') ON DUPLICATE KEY UPDATE status='pendente'`,[pid,req.user.id,req.user.tipo,JSON.stringify({leitura:true,escrita:false})]);await audit({usuarioId:req.user.id,acao:'SOLICITAR_VINCULO',entidade:'vinculos_cuidado',ip:req.ip});res.status(201).json({message:'Solicitação enviada.'});}catch(e){res.status(500).json({error:'Erro ao solicitar vínculo.'});}});
router.patch('/:id',async(req,res)=>{try{const status=req.body?.status;if(!['ativo','revogado'].includes(status))return res.status(400).json({error:'Status inválido.'});const [r]=await db.execute('SELECT * FROM vinculos_cuidado WHERE id=? LIMIT 1',[req.params.id]);if(!r.length)return res.status(404).json({error:'Vínculo não encontrado.'});const v=r[0];if(Number(v.paciente_id)!==Number(req.user.id))return res.status(403).json({error:'Somente o paciente pode autorizar este vínculo.'});await db.execute('UPDATE vinculos_cuidado SET status=?, permissoes=? WHERE id=?',[status,JSON.stringify(req.body.permissoes||{leitura:true,escrita:false}),req.params.id]);await audit({usuarioId:req.user.id,acao:'ATUALIZAR_VINCULO',entidade:'vinculos_cuidado',entidadeId:req.params.id,ip:req.ip});res.json({message:'Vínculo atualizado.'});}catch(e){res.status(500).json({error:'Erro ao atualizar vínculo.'});}});
module.exports=router;
